# Generated by Django 4.2.6 on 2023-10-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_gender_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="%Y/%m/%d"),
        ),
    ]
